//! QEMU integration test: PartitionSpec builder with peripheral region.
//!
//! Boots a partition using `PartitionSpec::entry(fn).with_peripherals()`
//! via `init_kernel`.  P0 receives MPU access to the UART0 region and
//! performs a volatile write + read-back to prove the access was granted.
//! Success is reported via semihosting.
//!
//! Run:
//!   cargo run --example builder_periph_test --features qemu,log-semihosting \
//!     --target thumbv7m-none-eabi --release
#![no_std]
#![no_main]
#![allow(incomplete_features)]
#![feature(generic_const_exprs)]

use core::sync::atomic::{AtomicU32, Ordering};
use cortex_m_rt::{entry, exception};
use cortex_m_semihosting::hprintln;
#[allow(unused_imports)]
use kernel::kpanic as _;
use kernel::{
    partition::MpuRegion,
    scheduler::{ScheduleEntry, ScheduleTable},
    DebugEnabled, MsgMinimal, PartitionEntry, PartitionSpec, Partitions2, PortsTiny, SyncMinimal,
};
#[allow(clippy::single_component_path_imports)]
use plib;

const UART0_BASE: u32 = 0x4000_C000;
const UART0_SIZE: u32 = 4096;

/// Static peripheral region array for the PartitionSpec builder.
static PERIPH_REGIONS: [MpuRegion; 1] = [MpuRegion::new(
    UART0_BASE,
    UART0_SIZE,
    kernel::mpu::AP_FULL_ACCESS,
)];

/// Result flag: 0 = not started, 1 = write+readback OK.
static RESULT: AtomicU32 = AtomicU32::new(0);

kernel::kernel_config!(
    TestConfig < Partitions2,
    SyncMinimal,
    MsgMinimal,
    PortsTiny,
    DebugEnabled > {}
);

/// P0: write to UART0 DR via raw volatile access, then signal success.
const _: PartitionEntry = p0_entry;
extern "C" fn p0_entry() -> ! {
    // UART0 Data Register is at base + 0x000.
    let dr_addr = UART0_BASE as *mut u32;

    // Write a known byte to DR.  If the MPU did not grant access this
    // will trigger a MemManage fault and we never reach the store below.
    // SAFETY: UART0 DR is a valid MMIO register on lm3s6965evb.  We have
    // MPU-granted access to the UART0 region.
    unsafe {
        core::ptr::write_volatile(dr_addr, 0x41); // 'A'
    }

    // Read back — on QEMU the value in DR is implementation-defined but
    // the read itself must not fault.
    // SAFETY: UART0 DR is a valid MMIO register on lm3s6965evb and we have
    // MPU-granted access to the UART0 region.
    let _readback: u32 = unsafe { core::ptr::read_volatile(dr_addr) };

    // If we reach here the MPU granted access successfully.
    // TODO: could assert readback value or use a multi-stage flag to make the
    // write/read success more explicit before signaling the harness.
    RESULT.store(1, Ordering::Release);

    loop {
        let _ = plib::sys_yield();
    }
}

/// P1: idle partition (two-partition minimum for round-robin schedule).
const _: PartitionEntry = p1_entry;
extern "C" fn p1_entry() -> ! {
    loop {
        let _ = plib::sys_yield();
    }
}

kernel::define_unified_harness!(TestConfig, |tick, _k| {
    let r = RESULT.load(Ordering::Acquire);
    if r == 1 {
        hprintln!("builder_periph_test: PASS peripheral write OK");
        kernel::kexit!(success);
    }
    if tick >= 200 {
        hprintln!("builder_periph_test: FAIL timeout (state={})", r);
        kernel::kexit!(failure);
    }
});

#[entry]
fn main() -> ! {
    let p = cortex_m::Peripherals::take().expect("peripherals");
    hprintln!(
        "=== {} v{} ===",
        env!("CARGO_PKG_NAME"),
        env!("CARGO_PKG_VERSION")
    );
    hprintln!("builder_periph_test: start");

    // --- Kernel setup via init_kernel + boot ---
    let mut sched = ScheduleTable::<{ TestConfig::SCHED }>::new();
    sched.add(ScheduleEntry::new(0, 4)).expect("sched 0");
    sched.add_system_window(1).expect("sys0");
    sched.add(ScheduleEntry::new(1, 2)).expect("sched 1");
    sched.add_system_window(1).expect("sys1");

    let parts: [PartitionSpec; TestConfig::N] = [
        PartitionSpec::entry(p0_entry).with_peripherals(&PERIPH_REGIONS),
        PartitionSpec::entry(p1_entry),
    ];

    // TODO: reviewer false positive — init_kernel, store_kernel, and boot are
    // generated by define_unified_harness! (via @impl_compat), not imported.
    let mut k = init_kernel(sched, &parts).expect("init_kernel");
    store_kernel(&mut k);
    match boot(p).expect("boot") {}
}
