//! QEMU test: pend IRQ 0 + IRQ 1 back-to-back in the same SysTick tick.
//! Validates dispatch handler processes simultaneous IRQs to separate partitions.
#![no_std]
#![no_main]
#![allow(incomplete_features)]
#![feature(generic_const_exprs)]

use core::sync::atomic::{AtomicU32, Ordering};
use cortex_m_rt::{entry, exception};
use cortex_m_semihosting::{debug, hprintln};
use kernel::partition::PartitionConfig;
use kernel::scheduler::ScheduleTable;
use kernel::svc::{Kernel, SvcError};
use kernel::syscall::SYS_EVT_WAIT;
use kernel::{DebugEnabled, MsgMinimal, Partitions2, PortsTiny, SyncMinimal};

kernel::compose_kernel_config!(SimulIrqConfig<Partitions2, SyncMinimal, MsgMinimal, PortsTiny, DebugEnabled>);

// Bind IRQ 0 → partition 0, event 0x01; IRQ 1 → partition 1, event 0x02.
kernel::bind_interrupts!(SimulIrqConfig, 70,
    0 => (0, 0x01),
    1 => (1, 0x02),
);

const NUM_PARTITIONS: usize = 2;
const STACK_WORDS: usize = SimulIrqConfig::STACK_WORDS;

/// Incremented by partition 0 after each successful `event_wait` return.
static P0_COUNT: AtomicU32 = AtomicU32::new(0);
/// Incremented by partition 1 after each successful `event_wait` return.
static P1_COUNT: AtomicU32 = AtomicU32::new(0);

kernel::define_unified_harness!(SimulIrqConfig, |tick, _k| {
    // Verify counts are still zero before pending (no spurious early delivery).
    if tick == 1 {
        let c0 = P0_COUNT.load(Ordering::Acquire);
        let c1 = P1_COUNT.load(Ordering::Acquire);
        if c0 != 0 || c1 != 0 {
            hprintln!(
                "irq_simultaneous_test: FAIL pre-pend (p0={}, p1={})",
                c0,
                c1
            );
            debug::exit(debug::EXIT_FAILURE);
        }
    }
    // Pend BOTH IRQs back-to-back in the same SysTick tick.
    if tick == 2 {
        // TODO: reviewer false positive — IrqNr implements InterruptNumber;
        // identical pattern used in irq_multi_test, irq_ack_test, irq_kernel_clears_test
        #[cfg(target_arch = "arm")]
        {
            cortex_m::peripheral::NVIC::pend(kernel::irq_dispatch::IrqNr(0));
            cortex_m::peripheral::NVIC::pend(kernel::irq_dispatch::IrqNr(1));
        }
        hprintln!(
            "irq_simultaneous_test: pended IRQ 0 + IRQ 1 at tick {}",
            tick
        );
    }
    if tick >= 8 {
        let c0 = P0_COUNT.load(Ordering::Acquire);
        let c1 = P1_COUNT.load(Ordering::Acquire);
        if c0 > 0 && c1 > 0 {
            hprintln!("irq_simultaneous_test: PASS (p0={}, p1={})", c0, c1);
            debug::exit(debug::EXIT_SUCCESS);
        }
    }
    if tick >= 12 {
        let c0 = P0_COUNT.load(Ordering::Acquire);
        let c1 = P1_COUNT.load(Ordering::Acquire);
        hprintln!("irq_simultaneous_test: FAIL (p0={}, p1={})", c0, c1);
        debug::exit(debug::EXIT_FAILURE);
    }
});

extern "C" fn p0_main() -> ! {
    loop {
        let rc = kernel::svc!(SYS_EVT_WAIT, 0u32, 0x01u32, 0u32);
        if SvcError::is_error(rc) {
            hprintln!(
                "irq_simultaneous_test: p0 FAIL (event_wait rc=0x{:08X})",
                rc
            );
            debug::exit(debug::EXIT_FAILURE);
        }
        P0_COUNT.fetch_add(1, Ordering::Release);
    }
}

extern "C" fn p1_main() -> ! {
    loop {
        let rc = kernel::svc!(SYS_EVT_WAIT, 0u32, 0x02u32, 0u32);
        if SvcError::is_error(rc) {
            hprintln!(
                "irq_simultaneous_test: p1 FAIL (event_wait rc=0x{:08X})",
                rc
            );
            debug::exit(debug::EXIT_FAILURE);
        }
        P1_COUNT.fetch_add(1, Ordering::Release);
    }
}

#[entry]
fn main() -> ! {
    let mut p = cortex_m::Peripherals::take().expect("irq_simultaneous_test: Peripherals::take");
    hprintln!("irq_simultaneous_test: start");

    let sched = ScheduleTable::<{ SimulIrqConfig::SCHED }>::round_robin(2, 3)
        .expect("irq_simultaneous_test: round_robin");

    let cfgs = PartitionConfig::sentinel_array::<NUM_PARTITIONS>(STACK_WORDS);

    let k = Kernel::<SimulIrqConfig>::create(sched, &cfgs)
        .expect("irq_simultaneous_test: Kernel::create");

    // TODO: reviewer false positive — store_kernel, enable_bound_irqs, and boot are
    // generated by define_unified_harness! / bind_interrupts! macros, not explicit imports
    store_kernel(k);

    // Unmask bound IRQs so software-triggered pends fire.
    enable_bound_irqs(&mut p.NVIC, 0xC0);

    let parts: [(extern "C" fn() -> !, u32); NUM_PARTITIONS] = [(p0_main, 0), (p1_main, 0)];
    match boot(&parts, &mut p).expect("irq_simultaneous_test: boot") {}
}
