//! QEMU stress test: rapid PendSV context switches under fast SysTick.
//!
//! Validates the BASEPRI/PENDSVCLR fix by exercising maximum preemption
//! pressure:
//!
//! 1. Two partitions run tight loops, each incrementing an `AtomicU32`.
//! 2. SysTick fires every ~996 cycles (tick_period_us = 83 at 12 MHz).
//! 3. The SysTick hook explicitly pends PendSV on every tick, forcing
//!    context-switch attempts even when the scheduler wouldn't.
//! 4. After several major frames the hook checks that both counters
//!    advanced — proving no missed switches, no MPU faults, no hangs.
//!
//! Run:  cargo run --target thumbv7m-none-eabi --features qemu,log-semihosting --example pendsv_basepri_test
#![no_std]
#![no_main]
#![allow(incomplete_features)]
#![feature(generic_const_exprs)]

use core::sync::atomic::{AtomicU32, Ordering};
use cortex_m_rt::{entry, exception};
use cortex_m_semihosting::{debug, hprintln};
use kernel::partition::PartitionConfig;
use kernel::scheduler::ScheduleTable;
use kernel::svc::Kernel;
use kernel::{DebugEnabled, MsgMinimal, Partitions2, PortsTiny, SyncMinimal};

// Fast SysTick: 12 MHz * 83 µs / 1e6 = 996 cycles per tick.
kernel::compose_kernel_config!(
    Config < Partitions2,
    SyncMinimal,
    MsgMinimal,
    PortsTiny,
    DebugEnabled > {
        tick_period_us = 83;
    }
);

const NUM_PARTITIONS: usize = 2;
const STACK_WORDS: usize = Config::STACK_WORDS;

/// Minimum tick count before checking (≈10 major frames of 2 ticks each).
const CHECK_TICK: u32 = 20;
/// Hard timeout — if we reach this tick without passing, declare failure.
const TIMEOUT_TICK: u32 = 200;
/// Minimum counter value to accept — ensures multiple context switches.
const MIN_COUNT: u32 = 4;

/// Incremented by partition 0 on every loop iteration.
static P0_COUNT: AtomicU32 = AtomicU32::new(0);
/// Incremented by partition 1 on every loop iteration.
static P1_COUNT: AtomicU32 = AtomicU32::new(0);

kernel::define_unified_harness!(Config, |tick, _k| {
    // Pend PendSV on every tick to maximise preemption pressure.
    #[cfg(target_arch = "arm")]
    cortex_m::peripheral::SCB::set_pendsv();

    if tick >= CHECK_TICK {
        let c0 = P0_COUNT.load(Ordering::Acquire);
        let c1 = P1_COUNT.load(Ordering::Acquire);
        if c0 >= MIN_COUNT && c1 >= MIN_COUNT {
            hprintln!("pendsv_basepri_test: PASS (p0={}, p1={})", c0, c1);
            debug::exit(debug::EXIT_SUCCESS);
        }
    }
    if tick >= TIMEOUT_TICK {
        let c0 = P0_COUNT.load(Ordering::Acquire);
        let c1 = P1_COUNT.load(Ordering::Acquire);
        hprintln!("pendsv_basepri_test: FAIL (p0={}, p1={})", c0, c1);
        debug::exit(debug::EXIT_FAILURE);
    }
});

extern "C" fn p0_main() -> ! {
    loop {
        P0_COUNT.fetch_add(1, Ordering::Release);
        cortex_m::asm::nop();
    }
}

extern "C" fn p1_main() -> ! {
    loop {
        P1_COUNT.fetch_add(1, Ordering::Release);
        cortex_m::asm::nop();
    }
}

#[entry]
fn main() -> ! {
    let mut p = cortex_m::Peripherals::take().expect("pendsv_basepri_test: Peripherals::take");
    hprintln!("pendsv_basepri_test: start");

    // 2 partitions, 1 tick per slot → major frame = 2 ticks (~1992 cycles).
    let sched = ScheduleTable::<{ Config::SCHED }>::round_robin(NUM_PARTITIONS, 1)
        .expect("pendsv_basepri_test: sched");

    let cfgs = PartitionConfig::sentinel_array::<NUM_PARTITIONS>(STACK_WORDS);

    let k = Kernel::<Config>::create(sched, &cfgs).expect("pendsv_basepri_test: Kernel::create");

    // store_kernel and boot are generated by define_unified_harness!
    store_kernel(k);

    // TODO: parts array hard-codes entries; all tests follow this pattern since each partition has a distinct entry point
    let parts: [(extern "C" fn() -> !, u32); NUM_PARTITIONS] = [(p0_main, 0), (p1_main, 0)];
    match boot(&parts, &mut p).expect("pendsv_basepri_test: boot") {}
}
