//! QEMU smoke test: boot → yield → semaphore IPC → exit.
//!
//! Regression gate exercising the full kernel lifecycle:
//!
//! 1. Kernel boots with two partitions via `define_unified_harness!`.
//! 2. Round-robin scheduler gives each partition 3 ticks.
//! 3. Partition 0 signals semaphore 0 (count 0→1), then calls SYS_YIELD.
//! 4. Partition 1 waits on semaphore 0, records rc (0=blocked, 1=immediate).
//! 5. SysTick callback verifies all three return codes, exits via `kexit!`.
//!
//! Run:  cargo run --target thumbv7m-none-eabi --features qemu,log-semihosting --example qemu_smoke
#![no_std]
#![no_main]
#![allow(incomplete_features)]
#![feature(generic_const_exprs)]

use core::sync::atomic::{AtomicU32, Ordering};
use cortex_m_rt::{entry, exception};
use cortex_m_semihosting::hprintln;
#[allow(unused_imports)]
use kernel::kpanic as _;
use kernel::scheduler::ScheduleTable;
use kernel::semaphore::Semaphore;
use kernel::{
    DebugEnabled, MsgMinimal, PartitionEntry, PartitionSpec, Partitions2, PortsTiny, SyncMinimal,
};

kernel::compose_kernel_config!(SmokeConfig<Partitions2, SyncMinimal, MsgMinimal, PortsTiny, DebugEnabled>);

const NUM_PARTITIONS: usize = SmokeConfig::N;
const TIMEOUT_TICKS: u32 = 50;

/// SYS_YIELD success return code.
const YIELD_OK: u32 = 0;
/// SYS_SEM_SIGNAL success return code.
const SEM_SIGNAL_OK: u32 = 0;
/// SYS_SEM_WAIT returns 1 when acquired immediately (count > 0),
/// or 0 when the partition blocked and was later unblocked by a signal.
const SEM_WAIT_IMMEDIATE: u32 = 1;
const SEM_WAIT_UNBLOCKED: u32 = 0;
/// Sentinel: partition has not yet executed its syscall.
const NOT_YET: u32 = 0xDEAD_C0DE;

/// Partition 0 stores SYS_YIELD return code here.
static YIELD_RC: AtomicU32 = AtomicU32::new(NOT_YET);
/// Partition 0 stores SYS_SEM_SIGNAL return code here.
static SIG_RC: AtomicU32 = AtomicU32::new(NOT_YET);
/// Partition 1 stores SYS_SEM_WAIT return code here.
static WAIT_RC: AtomicU32 = AtomicU32::new(NOT_YET);

// TODO: hprintln!/kexit! in SysTick ISR is heavy for an interrupt handler;
// acceptable for QEMU smoke tests but must not be used in production code.
kernel::define_unified_harness!(SmokeConfig, |tick, _k| {
    let y = YIELD_RC.load(Ordering::Acquire);
    let sig = SIG_RC.load(Ordering::Acquire);
    let wait = WAIT_RC.load(Ordering::Acquire);

    // Guard: wait until all partitions have executed their syscalls.
    if y == NOT_YET || sig == NOT_YET || wait == NOT_YET {
        if tick >= TIMEOUT_TICKS {
            hprintln!(
                "qemu_smoke: FAIL timeout (yield={:#x}, sig={:#x}, wait={:#x})",
                y,
                sig,
                wait
            );
            kernel::kexit!(failure);
        }
        return;
    }

    let wait_ok = wait == SEM_WAIT_IMMEDIATE || wait == SEM_WAIT_UNBLOCKED;
    if y == YIELD_OK && sig == SEM_SIGNAL_OK && wait_ok {
        hprintln!("qemu_smoke: PASS (yield={}, sig={}, wait={})", y, sig, wait);
        kernel::kexit!(success);
    } else {
        hprintln!(
            "qemu_smoke: FAIL (yield={:#x} expected {:#x}, sig={:#x} expected {:#x}, wait={:#x} expected 0 or 1)",
            y, YIELD_OK, sig, SEM_SIGNAL_OK, wait
        );
        kernel::kexit!(failure);
    }
});

const _: PartitionEntry = p0_main;
extern "C" fn p0_main() -> ! {
    // Signal first so the semaphore count is >0 before P1 runs.
    // TODO: SemaphoreId call-site fix from ce7dd01; included here for build correctness
    let rc = plib::sys_sem_signal(plib::SemaphoreId::new(0)).unwrap_or(u32::MAX);
    SIG_RC.store(rc, Ordering::Release);
    // Yield voluntarily — exercises SYS_YIELD and triggers context switch.
    let rc = plib::sys_yield().unwrap_or(u32::MAX);
    YIELD_RC.store(rc, Ordering::Release);
    loop {
        cortex_m::asm::nop();
    }
}

const _: PartitionEntry = p1_main;
extern "C" fn p1_main() -> ! {
    // TODO: SemaphoreId call-site fix from ce7dd01; included here for build correctness
    let rc = plib::sys_sem_wait(plib::SemaphoreId::new(0)).unwrap_or(u32::MAX);
    WAIT_RC.store(rc, Ordering::Release);
    loop {
        cortex_m::asm::nop();
    }
}

// NOTE: `store_kernel` and `boot` are generated by `define_unified_harness!`
// (via `define_unified_kernel!`) — they are not explicit imports.
#[entry]
fn main() -> ! {
    let p = cortex_m::Peripherals::take().expect("qemu_smoke: Peripherals::take");
    hprintln!(
        "=== {} v{} ===",
        env!("CARGO_PKG_NAME"),
        env!("CARGO_PKG_VERSION")
    );
    hprintln!("qemu_smoke: start");

    let sched = ScheduleTable::<{ SmokeConfig::SCHED }>::round_robin(2, 3)
        .expect("qemu_smoke: round_robin");

    let parts: [PartitionSpec; NUM_PARTITIONS] = [
        PartitionSpec::new(p0_main as PartitionEntry, 0),
        PartitionSpec::new(p1_main as PartitionEntry, 0),
    ];
    let mut k = init_kernel(sched, &parts).expect("qemu_smoke: Kernel::create");
    k.semaphores_mut()
        .add(Semaphore::new(0, 1))
        .expect("qemu_smoke: add semaphore");
    store_kernel(&mut k);

    match boot(p).expect("qemu_smoke: boot") {}
}
