//! QEMU smoke test: 2-partition semaphore IPC under QEMU.
//!
//! Verifies the full boot → schedule → IPC → exit path:
//!
//! 1. Kernel boots with two partitions via `define_unified_harness!`.
//! 2. Round-robin scheduler gives each partition 3 ticks.
//! 3. Partition 0 signals semaphore 0 (count 0→1), records rc=0.
//! 4. Partition 1 waits on semaphore 0 (count 1→0), records rc=SEM_ACQUIRED.
//! 5. SysTick callback verifies both return codes, exits via semihosting.
//!
//! Run:  cargo run --target thumbv7m-none-eabi --features qemu,log-semihosting --example qemu_smoke
#![no_std]
#![no_main]
#![allow(incomplete_features)]
#![feature(generic_const_exprs)]

use core::sync::atomic::{AtomicU32, Ordering};
use cortex_m_rt::{entry, exception};
use cortex_m_semihosting::{debug, hprintln};
use kernel::partition::PartitionConfig;
use kernel::scheduler::ScheduleTable;
use kernel::semaphore::Semaphore;
use kernel::svc::Kernel;
use kernel::syscall::{SYS_SEM_SIGNAL, SYS_SEM_WAIT};
use kernel::{DebugEnabled, MsgMinimal, Partitions2, PortsTiny, SyncMinimal};
use panic_semihosting as _;

kernel::compose_kernel_config!(SmokeConfig<Partitions2, SyncMinimal, MsgMinimal, PortsTiny, DebugEnabled>);

const NUM_PARTITIONS: usize = SmokeConfig::N;
const STACK_WORDS: usize = SmokeConfig::STACK_WORDS;
const TIMEOUT_TICKS: u32 = 50;

/// SYS_SEM_SIGNAL success return code.
const SEM_SIGNAL_OK: u32 = 0;
/// SYS_SEM_WAIT returns 1 when the semaphore was acquired immediately
/// (count was > 0 and decremented without blocking).
const SEM_ACQUIRED: u32 = 1;
/// Sentinel: partition has not yet executed its syscall.
const NOT_YET: u32 = u32::MAX;

/// Partition 0 stores SYS_SEM_SIGNAL return code here.
static SIG_RC: AtomicU32 = AtomicU32::new(NOT_YET);
/// Partition 1 stores SYS_SEM_WAIT return code here.
static WAIT_RC: AtomicU32 = AtomicU32::new(NOT_YET);

// TODO: hprintln!/debug::exit in SysTick ISR is heavy for an interrupt handler;
// acceptable for QEMU smoke tests but must not be used in production code.
kernel::define_unified_harness!(SmokeConfig, NUM_PARTITIONS, STACK_WORDS, |tick, _k| {
    let sig = SIG_RC.load(Ordering::Acquire);
    let wait = WAIT_RC.load(Ordering::Acquire);

    // Guard: wait until both partitions have executed their syscalls.
    if sig == NOT_YET || wait == NOT_YET {
        if tick >= TIMEOUT_TICKS {
            hprintln!(
                "qemu_smoke: FAIL timeout (sig={:#x}, wait={:#x})",
                sig,
                wait
            );
            debug::exit(debug::EXIT_FAILURE);
        }
        return;
    }

    if sig == SEM_SIGNAL_OK && wait == SEM_ACQUIRED {
        hprintln!("qemu_smoke: PASS (sig={}, wait={})", sig, wait);
        debug::exit(debug::EXIT_SUCCESS);
    } else {
        hprintln!("qemu_smoke: FAIL (sig={}, wait={})", sig, wait);
        debug::exit(debug::EXIT_FAILURE);
    }
});

extern "C" fn p0_main() -> ! {
    let rc = kernel::svc!(SYS_SEM_SIGNAL, 0u32, 0u32, 0u32);
    SIG_RC.store(rc, Ordering::Release);
    loop {
        cortex_m::asm::nop();
    }
}

extern "C" fn p1_main() -> ! {
    let rc = kernel::svc!(SYS_SEM_WAIT, 0u32, 0u32, 0u32);
    WAIT_RC.store(rc, Ordering::Release);
    loop {
        cortex_m::asm::nop();
    }
}

// NOTE: `store_kernel` and `boot` are generated by `define_unified_harness!`
// (via `define_unified_kernel!`) — they are not explicit imports.
// TODO: reviewer false positive — these symbols are macro-generated, not missing imports.
#[entry]
fn main() -> ! {
    let mut p = cortex_m::Peripherals::take().expect("qemu_smoke: Peripherals::take");
    hprintln!("qemu_smoke: start");

    let sched = ScheduleTable::<{ SmokeConfig::SCHED }>::round_robin(2, 3)
        .expect("qemu_smoke: round_robin");

    let cfgs = PartitionConfig::sentinel_array::<NUM_PARTITIONS>(STACK_WORDS);

    let mut k = Kernel::<SmokeConfig>::create(sched, &cfgs).expect("qemu_smoke: Kernel::create");

    // Semaphore 0: initial count=0, max=1.
    // P0 signals (0→1), then P1 waits and acquires (1→0).
    k.semaphores_mut()
        .add(Semaphore::new(0, 1))
        .expect("qemu_smoke: add semaphore");

    store_kernel(k);

    let parts: [(extern "C" fn() -> !, u32); NUM_PARTITIONS] = [(p0_main, 0), (p1_main, 0)];
    match boot(&parts, &mut p).expect("qemu_smoke: boot") {}
}
