//! PendSV context-switch handler for Cortex-M partitions.
//!
//! Provides the [`define_pendsv!`] macro that emits the PendSV handler assembly.
//! This avoids each example duplicating the context-switch logic while
//! keeping the assembly out of binaries that do not need it (since
//! `global_asm!` in a library crate is linked into every binary).
//!
//! - `define_pendsv!()` — static mode, no compile-time offset assertions.
//! - `define_pendsv!(Config)` — static mode with compile-time offset assertions.
//! - `define_pendsv!(dynamic: STRATEGY, Config)` — dynamic mode, also programs MPU R4-R7.
//!
//! # Architecture
//!
//! The PendSV assembly accesses kernel state directly via struct field offsets.
//! The linker symbol `__kernel_state_start` provides the base address, and
//! compile-time offset constants (`KERNEL_CURRENT_PARTITION_OFFSET`, etc.)
//! allow direct field access without function call overhead. This is safe
//! because PendSV runs at the lowest exception priority (0xFF), guaranteeing
//! exclusive access to kernel state without needing critical sections.
//!
//! The offset constants are generated by [`define_unified_kernel!`] using
//! `core::mem::offset_of!` and exported as `#[no_mangle]` symbols. Both
//! `Kernel<C>` and `PartitionCore` use `#[repr(C)]` for deterministic layout.
//!
//! # Requirements
//!
//! The binary must invoke [`define_unified_kernel!`] which provides:
//! - Kernel struct offset constants for direct memory access
//! - The `__kernel_state_start` linker symbol via `.kernel_state` section
//!
//! The context save/restore logic is implemented as linkable functions in
//! [`pendsv_asm`](crate::pendsv_asm):
//! - `pendsv_context_save` — saves r4-r11 and PSP using direct offset access
//! - `pendsv_context_restore` — restores r4-r11 and PSP using direct offset access
//! - `pendsv_return_unprivileged` — sets CONTROL.nPRIV=1 and returns
//!
//! # Usage
//!
//! ```ignore
//! kernel::define_pendsv!();                    // static mode
//! kernel::define_pendsv!(dynamic: STRATEGY);   // dynamic mode
//! ```

// --- ICSR constants for PendSV assembly ----------------------------------

/// Interrupt Control and State Register address.
/// ARMv7-M SCS base (0xE000\_E000) + ICSR offset (0xD04).
pub const ICSR_ADDR: u32 = 0xE000_ED04;

/// PENDSVCLR: bit 27 of ICSR. Writing 1 clears PendSV pending.
pub const PENDSVCLR_BIT: u32 = 1 << 27;

/// PENDSTCLR: bit 25 of ICSR. Writing 1 clears SysTick pending.
pub const PENDSTCLR_BIT: u32 = 1 << 25;

/// Combined PENDSVCLR | PENDSTCLR for clearing both pending bits.
pub const PENDSV_SYSTICK_CLEAR: u32 = PENDSVCLR_BIT | PENDSTCLR_BIT;

/// PENDSTSET: bit 26 of ICSR. Writing 1 sets SysTick pending.
pub const PENDSTSET_BIT: u32 = 1 << 26;

/// Maximum byte offset addressable by a Thumb2 `LDR Rt, [Rn, #imm12]`
/// instruction. The encoding provides a 12-bit unsigned immediate,
/// giving a range of 0..=4095 (i.e. offsets must be strictly less than 4096).
pub const THUMB2_LDR_MAX_OFFSET: usize = 4096;

// Compile-time validation against ARMv7-M specification values.
const _: () = {
    assert!(ICSR_ADDR == 0xE000_ED04);
    assert!(PENDSVCLR_BIT == 0x0800_0000);
    assert!(PENDSTCLR_BIT == 0x0200_0000);
    assert!(PENDSV_SYSTICK_CLEAR == 0x0A00_0000);
    assert!(PENDSTSET_BIT == 0x0400_0000);
};

/// Emit the PendSV context-switch handler. See module docs for modes.
#[macro_export]
macro_rules! define_pendsv {
    // TODO: reviewer false positive — the internal dispatch tag is `@impl`,
    // a standard Rust macro pattern; no build-artifact path is present.
    // Public entry points delegate to the internal @impl arm.

    // Static mode without $Config — no struct-level assertions possible.
    // Prefer the ($Config:ty) arm when $Config is available.
    () => { $crate::define_pendsv!(@impl ""); };

    // Static mode with $Config — adds compile-time offset assertions.
    ($Config:ty) => {
        $crate::define_pendsv!(@assert_offsets $Config);
        $crate::define_pendsv!(@impl "");
    };
    (dynamic: $strategy:ident, $Config:ty) => {
        /// Rust shim called from the PendSV assembly to program MPU
        /// regions R0-R3 (cached base) + R4-R7 (dynamic strategy).
        #[cfg(feature = "dynamic-mpu")]
        #[no_mangle]
        extern "C" fn __pendsv_program_mpu() {
            // SAFETY: PendSV is the lowest-priority exception, so no
            // other exception can preempt us while writing MPU registers.
            // `steal()` is sound because we have exclusive access to the
            // MPU peripheral at this priority level.
            let p = unsafe { cortex_m::Peripherals::steal() };
            // SAFETY: same exclusive-access argument as steal() above.
            // get_kernel_ptr returns the address of the static kernel storage;
            // it is non-null after init_kernel_state() which completes before
            // SysTick (and thus PendSV) is enabled.
            let kptr = unsafe { $crate::state::get_kernel_ptr::<$Config>() };
            debug_assert!(!kptr.is_null(), "kernel pointer is null in PendSV");
            let k = unsafe { &*kptr };
            let pid = k.next_partition();
            // Pre-compute dynamic region values before disabling MPU to
            // minimise the window where the MPU is off.
            let dynamic_values = $strategy.compute_region_values();
            // Single MPU disable/enable cycle for both base (R0-R3) and
            // dynamic (R4-R7) regions.
            $crate::mpu::mpu_disable(&p.MPU);
            if let Some(pcb) = k.partitions().get(pid as usize) {
                $crate::mpu::write_cached_base_regions(&p.MPU, pcb);
            }
            for &(rbar, rasr) in &dynamic_values {
                $crate::mpu::configure_region(&p.MPU, rbar, rasr);
            }
            $crate::mpu::mpu_enable(&p.MPU);
        }

        $crate::define_pendsv!(@assert_offsets $Config);
        $crate::define_pendsv!(@impl "bl __pendsv_program_mpu");
    };

    // Internal: compile-time assertions for PendSV assembly invariants.
    (@assert_offsets $Config:ty) => {
        const _: () = {
            type K = $crate::svc::Kernel<$Config>;
            type C = <$Config as $crate::config::KernelConfig>::Core;

            // All offsets must be < THUMB2_LDR_MAX_OFFSET (Thumb2 ldr 12-bit unsigned immediate).
            assert!(::core::mem::offset_of!(K, current_partition) < $crate::pendsv::THUMB2_LDR_MAX_OFFSET,
                "KERNEL_CURRENT_PARTITION_OFFSET exceeds Thumb2 ldr range");
            assert!(::core::mem::offset_of!(K, ticks_dropped) < $crate::pendsv::THUMB2_LDR_MAX_OFFSET,
                "KERNEL_TICKS_DROPPED_OFFSET exceeds Thumb2 ldr range");
            assert!(::core::mem::offset_of!(K, core) < $crate::pendsv::THUMB2_LDR_MAX_OFFSET,
                "KERNEL_CORE_OFFSET exceeds Thumb2 ldr range");
            assert!(::core::mem::offset_of!(K, core) + ::core::mem::offset_of!(C, next_partition) < $crate::pendsv::THUMB2_LDR_MAX_OFFSET,
                "KERNEL_CORE_OFFSET + CORE_NEXT_PARTITION_OFFSET exceeds Thumb2 ldr range");
            assert!(::core::mem::offset_of!(K, core) + ::core::mem::offset_of!(C, partition_sp) < $crate::pendsv::THUMB2_LDR_MAX_OFFSET,
                "KERNEL_CORE_OFFSET + CORE_PARTITION_SP_OFFSET exceeds Thumb2 ldr range");
            assert!(::core::mem::offset_of!(K, core) + ::core::mem::offset_of!(C, partition_stack_limits) < $crate::pendsv::THUMB2_LDR_MAX_OFFSET,
                "KERNEL_CORE_OFFSET + CORE_PARTITION_STACK_LIMIT_OFFSET exceeds Thumb2 ldr range");

            // Field ordering: current_partition before core in Kernel.
            assert!(::core::mem::offset_of!(K, current_partition) < ::core::mem::offset_of!(K, core),
                "current_partition must precede core in Kernel layout");

            // Field ordering: next_partition before partition_sp in Core.
            assert!(::core::mem::offset_of!(C, next_partition) < ::core::mem::offset_of!(C, partition_sp),
                "next_partition must precede partition_sp in Core layout");

            // PendSV indexes partition_sp with `lsl r0, #2` (×4) — elements must be u32, stride 4.
            #[allow(unused)]
            fn _assert_sp_elem_is_u32_stride_4(c: &C) {
                let _: u32 = c.partition_sp[0];
                let _: [u8; 4] = c.partition_sp[0].to_ne_bytes();
            }

            // partition_sp combined offset must be 4-byte aligned for word-sized ldr/str.
            assert!((::core::mem::offset_of!(K, core) + ::core::mem::offset_of!(C, partition_sp)) % 4 == 0,
                "partition_sp must be 4-byte aligned");
        };
    };

    // Internal implementation: PendSV with PRIMASK critical section.
    // All callers use this single implementation path.
    (@impl $mpu_call:literal) => {
        #[cfg(target_arch = "arm")]
        // SAFETY: This assembly implements the PendSV exception handler which
        // performs partition context switches. The operations are sound because:
        //
        // 1. Single-core exclusivity + PRIMASK critical section: PendSV runs at
        //    the lowest exception priority (0xFF). PRIMASK (cpsid i / cpsie i)
        //    masks all exceptions with configurable priority around the MPU
        //    programming + next_partition read + context restore sequence,
        //    eliminating the TOCTOU race where SysTick could change
        //    next_partition between MPU programming and context restore (Bug
        //    14-numbat). PENDSVCLR|PENDSTCLR is written to ICSR before
        //    cpsie i to prevent a spurious tail-chained PendSV and a stale
        //    SysTick pending bit from consuming the incoming partition's
        //    quantum (Bug 16-pelican).
        //
        //    PRIMASK equivalence: During PendSV (Handler mode, priority 0xFF),
        //    PRIMASK and BASEPRI=SYSTICK_PRIORITY block the same set of
        //    exceptions — SysTick and all app IRQs (priority >= 0x20). SVCall
        //    (priority 0x00) is also masked by PRIMASK but cannot fire during
        //    Handler mode (requires Thread→Handler transition). HardFault (-1)
        //    and NMI (-2) are unaffected by PRIMASK. PRIMASK is simpler
        //    (2 instructions vs 4), needs no linker symbol, and works on all
        //    ARMv7-M hardware regardless of priority bit width — unlike BASEPRI
        //    which truncates to 0x00 (no masking) on 3-bit priority hardware
        //    such as LM3S6965/QEMU.
        //
        // 2. Boot sequence invariants: This handler assumes boot() has completed:
        //    - partition_sp[i] contains valid stack pointers for all partitions
        //      (initialized via init_stack_frame() during boot)
        //    - current_partition == 0xFF initially (sentinel for first switch)
        //    - next_partition contains a valid partition index (set by scheduler)
        //    - Exception priorities configured: SVCall < SysTick < PendSV (0xFF)
        //    These invariants are established before SysTick is enabled.
        //
        // 3. Offset constant validity: Kernel state fields are accessed directly
        //    via __kernel_state_start + compile-time field offsets. The offsets
        //    (KERNEL_CURRENT_PARTITION_OFFSET, KERNEL_CORE_OFFSET, etc.) are:
        //    - Computed using core::mem::offset_of! in define_unified_kernel!
        //    - Valid because Kernel<C> and PartitionCore use #[repr(C)] layout
        //    - Exported as #[no_mangle] symbols, linking the same values used here
        //
        // 4. Register convention compliance: The assembly follows ARM AAPCS.
        //    - Before pendsv_context_save: only r0-r3 (hardware-saved on
        //      exception entry) are used as scratch. r4-r11 are untouched,
        //      preserving the outgoing partition's callee-saved state for
        //      the save routine.
        //    - After save: r4-r11 are free for use as callee-saved working
        //      registers (e.g. r4 holds partition index, r5 holds kernel base).
        //    - lr is saved/restored around bl instructions
        //
        // 5. PSP/register save ordering: The outgoing partition's r4-r11 are
        //    pushed to its process stack before modifying kernel state.
        //    The incoming partition's registers are restored after all state
        //    updates complete, ensuring no register corruption.
        //
        // 6. MPU programming (dynamic mode only): When $mpu_call is non-empty,
        //    __pendsv_program_mpu is called AFTER saving the outgoing context
        //    and BEFORE restoring the incoming context, all within the PRIMASK
        //    critical section. This ensures MPU regions and the next_partition
        //    read are atomic with respect to SysTick, preventing the race where
        //    SysTick changes next_partition after MPU is already programmed.
        core::arch::global_asm!(
            concat!(
                r#"
            .syntax unified
            .thumb

            .global PendSV
            .type PendSV, %function
            .thumb_func

        PendSV:
            /* r4-r11 contain the outgoing partition's callee-saved registers
             * and must NOT be modified before pendsv_context_save. */

            /* Load current_partition using only r0-r3 (hardware-saved) */
            ldr     r0, =__kernel_state_start
            ldr     r1, =KERNEL_CURRENT_PARTITION_OFFSET
            ldr     r1, [r1]            /* r1 = offset value */
            ldrb    r1, [r0, r1]        /* r1 = current_partition */

            /* Skip save if current_partition == 0xFF (first switch) */
            cmp     r1, #0xFF
            beq     .Lpendsv_skip_save

            /* Save outgoing partition context: r0 = partition index */
            mov     r0, r1
            bl      pendsv_context_save

        .Lpendsv_skip_save:
            /* Load kernel base into r5 (safe now: context is saved) */
            ldr     r5, =__kernel_state_start

            /* --- Begin PRIMASK critical section: mask all configurable exceptions ---
             * CPSID I sets PRIMASK, preventing SysTick from preempting
             * between MPU programming and next_partition read, eliminating
             * the TOCTOU race (Bug 14-numbat). */
            cpsid   i

            /* Dynamic mode: program MPU regions (empty string = no-op) */
            "#,
                $mpu_call,
                r#"
            /* Load next_partition: kernel_base + KERNEL_CORE_OFFSET + CORE_NEXT_PARTITION_OFFSET */
            ldr     r0, =KERNEL_CORE_OFFSET
            ldr     r0, [r0]            /* r0 = core offset */
            add     r6, r5, r0          /* r6 = &kernel.core */

            ldr     r0, =CORE_NEXT_PARTITION_OFFSET
            ldr     r0, [r0]            /* r0 = next_partition offset within core */
            ldrb    r4, [r6, r0]        /* r4 = next_partition (callee-saved) */

            /* Skip restore if next partition has overflow sentinel
             * (race: SysTick may schedule faulted partition before
             * context_save writes the sentinel). */
            ldr     r0, =CORE_PARTITION_SP_OFFSET
            ldr     r0, [r0]
            add     r0, r6, r0          /* r0 = &partition_sp[0] */
            lsl     r1, r4, #2
            ldr     r1, [r0, r1]        /* r1 = partition_sp[next] */
            ldr     r0, =0xDEAD0001
            cmp     r1, r0
            beq     .Lpendsv_faulted_skip

            /* Store next_partition to current_partition */
            ldr     r0, =KERNEL_CURRENT_PARTITION_OFFSET
            ldr     r0, [r0]            /* r0 = current_partition offset */
            strb    r4, [r5, r0]        /* current_partition = next_partition */

            /* Restore incoming partition context: r0 = partition index */
            mov     r0, r4
            bl      pendsv_context_restore

        .Lpendsv_faulted_skip:
            /* --- End PRIMASK critical section ---
             * Clear PendSV and SysTick pending bits, then unmask.
             *
             * PENDSVCLR (bit 27) clears a spurious PendSV re-pended by
             * SysTick while masked. PENDSTCLR (bit 25) clears a stale
             * SysTick that would otherwise fire immediately and consume
             * the incoming partition's quantum (Bug 16-pelican).
             * When timer accuracy and partition liveness conflict,
             * liveness wins. The lost tick cost is ≤1ms in debug
             * builds; in release the critical section is sub-µs and
             * PENDSTCLR clears a bit already 0. */
            ldr     r0, ={icsr_addr}     /* ICSR address */
            mov     r1, #{pendsv_systick_clear}     /* PENDSVCLR | PENDSTCLR */
            str     r1, [r0]
            dsb                         /* ensure PENDSVCLR write completes */
            cpsie   i                   /* unmask all configurable exceptions */

            /* pendsv_return_unprivileged does not return.
             * r0 clobber above is safe: pendsv_return_unprivileged takes
             * no inputs (starts with `mrs r0, CONTROL`), and
             * pendsv_context_restore has no return value in r0 (outputs
             * via PSP/r4-r11 side effects per AAPCS). */
            bl      pendsv_return_unprivileged

            .size PendSV, . - PendSV
        "#
            ),
            icsr_addr = const $crate::pendsv::ICSR_ADDR,
            pendsv_systick_clear = const $crate::pendsv::PENDSV_SYSTICK_CLEAR,
        );
    };
}

/// Backwards compatibility wrapper.
#[cfg(feature = "dynamic-mpu")]
#[macro_export]
macro_rules! define_pendsv_dynamic {
    ($strategy:ident, $Config:ty) => { $crate::define_pendsv!(dynamic: $strategy, $Config); };
}

/// Offset of `stack_limit` within `PartitionControlBlock`.
pub const PCB_STACK_LIMIT_OFFSET: usize =
    core::mem::offset_of!(crate::partition::PartitionControlBlock, stack_limit);
crate::const_assert!(
    PCB_STACK_LIMIT_OFFSET < THUMB2_LDR_MAX_OFFSET,
    "PCB stack_limit offset exceeds Thumb2 ldr range"
);

#[cfg(test)]
mod tests {
    use crate::mpu::{partition_mpu_regions_or_deny_all, precompute_mpu_cache};
    use crate::partition::{MpuRegion, PartitionControlBlock};

    #[test]
    fn icsr_constants_match_armv7m_spec() {
        use super::{ICSR_ADDR, PENDSTCLR_BIT, PENDSTSET_BIT, PENDSVCLR_BIT, PENDSV_SYSTICK_CLEAR};

        // ICSR is at SCS base (0xE000_E000) + offset 0xD04.
        assert_eq!(ICSR_ADDR, 0xE000_ED04);

        // PENDSVCLR is bit 27 (write-1-to-clear).
        assert_eq!(PENDSVCLR_BIT, 1 << 27);
        assert_eq!(PENDSVCLR_BIT, 0x0800_0000);

        // PENDSTCLR is bit 25 (write-1-to-clear).
        assert_eq!(PENDSTCLR_BIT, 1 << 25);
        assert_eq!(PENDSTCLR_BIT, 0x0200_0000);

        // Combined value clears both pending bits.
        assert_eq!(PENDSV_SYSTICK_CLEAR, PENDSVCLR_BIT | PENDSTCLR_BIT);
        assert_eq!(PENDSV_SYSTICK_CLEAR, 0x0A00_0000);

        // PENDSTSET is bit 26 (write-1-to-set).
        assert_eq!(PENDSTSET_BIT, 0x0400_0000);

        // No bit overlaps among CLR/SET constants.
        assert_eq!(
            (PENDSVCLR_BIT | PENDSTCLR_BIT | PENDSTSET_BIT).count_ones(),
            3
        );
    }

    #[test]
    fn thumb2_ldr_max_offset_matches_architectural_limit() {
        // Thumb2 LDR (immediate, T3 encoding) uses a 12-bit unsigned offset:
        // range 0..=4095, so the exclusive upper bound is 2^12 = 4096.
        assert_eq!(super::THUMB2_LDR_MAX_OFFSET, 1 << 12);
        assert_eq!(super::THUMB2_LDR_MAX_OFFSET, 4096);
    }

    #[test]
    fn pcb_stack_limit_offset_matches_offset_of() {
        let actual = core::mem::offset_of!(PartitionControlBlock, stack_limit);
        assert_eq!(super::PCB_STACK_LIMIT_OFFSET, actual);
        assert!(actual < super::THUMB2_LDR_MAX_OFFSET);
    }

    #[test]
    fn sealed_cache_valid_for_pendsv() {
        let mut pcb = PartitionControlBlock::new(
            0,
            0x0800_0000,
            0x2000_0000,
            0x2000_0000 + 1024,
            MpuRegion::new(0x2000_0000, 1024, 0x0306_0000),
        );
        assert!(!pcb.cache_sealed());
        let expected = partition_mpu_regions_or_deny_all(&pcb);
        precompute_mpu_cache(&mut pcb).unwrap();
        assert!(pcb.cache_sealed());
        let base = pcb.cached_base_regions();
        assert!(base[0].0 != 0 || base[0].1 != 0, "R0 must be non-zero");
        assert_eq!(*base, expected);
    }
}
