//! PendSV context-switch handler for Cortex-M partitions.
//!
//! Provides reusable macros that emit the PendSV handler assembly.
//! This avoids each example duplicating the context-switch logic while
//! keeping the assembly out of binaries that do not need it (since
//! `global_asm!` in a library crate is linked into every binary).
//!
//! - [`define_pendsv!`] — standard context switch (register save/restore only).
//! - [`define_pendsv_dynamic!`] — context switch that also programs dynamic
//!   MPU regions R4-R7 via a [`DynamicStrategy`](crate::mpu_strategy::DynamicStrategy).
//!
//! # Architecture
//!
//! The PendSV assembly accesses kernel state directly via struct field offsets.
//! The linker symbol `__kernel_state_start` provides the base address, and
//! compile-time offset constants (`KERNEL_CURRENT_PARTITION_OFFSET`, etc.)
//! allow direct field access without function call overhead. This is safe
//! because PendSV runs at the lowest exception priority (0xFF), guaranteeing
//! exclusive access to kernel state without needing critical sections.
//!
//! The offset constants are generated by [`define_unified_kernel!`] using
//! `core::mem::offset_of!` and exported as `#[no_mangle]` symbols. Both
//! `Kernel<C>` and `PartitionCore` use `#[repr(C)]` for deterministic layout.
//!
//! # Requirements
//!
//! The binary must invoke [`define_unified_kernel!`] which provides:
//! - Kernel struct offset constants for direct memory access
//! - The `__kernel_state_start` linker symbol via `.kernel_state` section
//!
//! The context save/restore logic is implemented as linkable functions in
//! [`pendsv_asm`](crate::pendsv_asm):
//! - `pendsv_context_save` — saves r4-r11 and PSP using direct offset access
//! - `pendsv_context_restore` — restores r4-r11 and PSP using direct offset access
//! - `pendsv_return_unprivileged` — sets CONTROL.nPRIV=1 and returns
//!
//! # Usage
//!
//! ```ignore
//! // Standard (no MPU):
//! kernel::define_pendsv!();
//!
//! // Dynamic MPU — pass the DynamicStrategy static:
//! kernel::define_pendsv_dynamic!(STRATEGY);
//! ```

/// Emit the PendSV context-switch handler via `global_asm!`.
///
/// This macro defines a single canonical implementation of the PendSV
/// handler. Invoke it once at the crate root of any binary that performs
/// partition context switches.
///
/// The handler:
/// 1. Loads `current_partition` directly from kernel state — skips save if 0xFF.
/// 2. Calls `pendsv_context_save` to save r4-r11 and PSP.
/// 3. Loads `next_partition` directly, stores to `current_partition`.
/// 4. Calls `pendsv_context_restore` to restore r4-r11 and PSP.
/// 5. Calls `pendsv_return_unprivileged` to set CONTROL.nPRIV=1 and return.
///
/// # Implementation Note
///
/// The context save/restore logic is implemented as linkable functions in
/// [`pendsv_asm`](crate::pendsv_asm). These functions use direct struct
/// offset access to the `partition_sp` array, avoiding function call overhead.
#[macro_export]
macro_rules! define_pendsv {
    () => {
        #[cfg(target_arch = "arm")]
        // SAFETY: This assembly implements the PendSV exception handler which
        // performs partition context switches. The operations are sound because:
        //
        // 1. Exception priority exclusivity: PendSV is configured as the
        //    lowest-priority exception (priority 0xFF). It cannot preempt
        //    itself, and higher-priority exceptions (SysTick, SVC) complete
        //    before PendSV runs. This guarantees exclusive access to the
        //    partition state being saved/restored without needing critical sections.
        //
        // 2. Register convention compliance: The assembly follows ARM AAPCS.
        //    - r0-r3 are caller-saved scratch registers used for arguments
        //    - r4-r11 are callee-saved and explicitly preserved across calls
        //    - lr is saved/restored around bl instructions
        //    - The partition index is held in r4 (callee-saved) across calls
        //
        // 3. Direct memory access: Kernel state fields are accessed directly
        //    via __kernel_state_start + compile-time field offsets. The structs
        //    use #[repr(C)] for deterministic layout, and offsets are computed
        //    using core::mem::offset_of! in define_unified_kernel!.
        //
        // 4. PSP/register save ordering: The outgoing partition's r4-r11 are
        //    pushed to its process stack before modifying kernel state.
        //    The incoming partition's registers are restored after all state
        //    updates complete, ensuring no register corruption.
        core::arch::global_asm!(
            r#"
            .syntax unified
            .thumb

            .global PendSV
            .type PendSV, %function
            .thumb_func

        PendSV:
            /* Load kernel base address into r5 (callee-saved) */
            ldr     r5, =__kernel_state_start

            /* Load current_partition offset and read the field */
            ldr     r0, =KERNEL_CURRENT_PARTITION_OFFSET
            ldr     r0, [r0]            /* r0 = offset value */
            ldrb    r4, [r5, r0]        /* r4 = current_partition (callee-saved) */

            /* Skip save if current_partition == 0xFF (first switch) */
            cmp     r4, #0xFF
            beq     .Lpendsv_skip_save

            /* Save outgoing partition context: r0 = partition index */
            mov     r0, r4
            bl      pendsv_context_save

        .Lpendsv_skip_save:
            /* Load next_partition: kernel_base + KERNEL_CORE_OFFSET + CORE_NEXT_PARTITION_OFFSET */
            ldr     r0, =KERNEL_CORE_OFFSET
            ldr     r0, [r0]            /* r0 = core offset */
            add     r6, r5, r0          /* r6 = &kernel.core */

            ldr     r0, =CORE_NEXT_PARTITION_OFFSET
            ldr     r0, [r0]            /* r0 = next_partition offset within core */
            ldrb    r4, [r6, r0]        /* r4 = next_partition (callee-saved) */

            /* Store next_partition to current_partition */
            ldr     r0, =KERNEL_CURRENT_PARTITION_OFFSET
            ldr     r0, [r0]            /* r0 = current_partition offset */
            strb    r4, [r5, r0]        /* current_partition = next_partition */

            /* Restore incoming partition context: r0 = partition index */
            mov     r0, r4
            bl      pendsv_context_restore

            /* pendsv_return_unprivileged does not return */
            bl      pendsv_return_unprivileged

            .size PendSV, . - PendSV
        "#
        );
    };
}

/// Emit a PendSV handler that programs dynamic MPU regions before switching.
///
/// Like [`define_pendsv!`], but the generated handler calls a Rust shim
/// (`__pendsv_program_mpu`) that invokes
/// [`DynamicStrategy::program_regions`](crate::mpu_strategy::DynamicStrategy::program_regions)
/// just before restoring the incoming partition's context.  This ensures
/// the MPU is reconfigured **inside PendSV** — the lowest-priority
/// exception — rather than in SysTick, eliminating the race where code
/// runs with a stale memory map.
///
/// Like `define_pendsv!`, the handler also sets `CONTROL.nPRIV = 1`
/// before returning to Thread mode so the partition runs unprivileged.
///
/// # Arguments
///
/// `$strategy` — the identifier of a `static DynamicStrategy` that the
/// SysTick handler has already called `configure_partition` on.
///
/// # Requirements
///
/// Same symbol requirements as [`define_pendsv!`].
///
/// # Implementation Note
///
/// The context save/restore logic is implemented as linkable functions in
/// [`pendsv_asm`](crate::pendsv_asm). These functions use direct struct
/// offset access, shared between `define_pendsv!` and `define_pendsv_dynamic!`.
///
/// # Example
///
/// ```ignore
/// static STRATEGY: DynamicStrategy = DynamicStrategy::new();
/// kernel::define_pendsv_dynamic!(STRATEGY);
/// ```
#[cfg(feature = "dynamic-mpu")]
#[macro_export]
macro_rules! define_pendsv_dynamic {
    ($strategy:ident) => {
        /// Rust shim called from the PendSV assembly to program dynamic
        /// MPU regions R4-R7.  Exposed as `#[no_mangle]` so the assembly
        /// can `bl` to it.
        #[no_mangle]
        extern "C" fn __pendsv_program_mpu() {
            // SAFETY: PendSV is the lowest-priority exception, so no
            // other exception can preempt us while writing MPU registers.
            // `steal()` is sound because we have exclusive access to the
            // MPU peripheral at this priority level.
            let p = unsafe { cortex_m::Peripherals::steal() };
            $strategy.program_regions(&p.MPU);
        }

        #[cfg(target_arch = "arm")]
        // SAFETY: This assembly implements the PendSV exception handler with
        // dynamic MPU region programming. The operations are sound because:
        //
        // 1. Exception priority exclusivity: PendSV is configured as the
        //    lowest-priority exception (priority 0xFF). It cannot preempt
        //    itself, and higher-priority exceptions (SysTick, SVC) complete
        //    before PendSV runs. This guarantees exclusive access to the
        //    partition state and MPU registers without needing critical sections.
        //
        // 2. Register convention compliance: The assembly follows ARM AAPCS.
        //    - r0-r3 are caller-saved scratch registers used for arguments
        //    - r4-r11 are callee-saved and explicitly preserved across calls
        //    - lr is saved/restored around bl instructions
        //    - The partition index is held in r4 (callee-saved) across calls
        //
        // 3. Direct memory access: Kernel state fields are accessed directly
        //    via __kernel_state_start + compile-time field offsets. The structs
        //    use #[repr(C)] for deterministic layout, and offsets are computed
        //    using core::mem::offset_of! in define_unified_kernel!.
        //
        // 4. MPU programming timing: __pendsv_program_mpu is called AFTER saving
        //    the outgoing context and BEFORE restoring the incoming context.
        //    This ensures the MPU is reconfigured for the incoming partition
        //    before any of its code executes, eliminating TOCTOU races.
        //
        // 5. PSP/register save ordering: Same guarantees as define_pendsv!.
        core::arch::global_asm!(
            r#"
            .syntax unified
            .thumb

            .global PendSV
            .type PendSV, %function
            .thumb_func

        PendSV:
            /* Load kernel base address into r5 (callee-saved) */
            ldr     r5, =__kernel_state_start

            /* Load current_partition offset and read the field */
            ldr     r0, =KERNEL_CURRENT_PARTITION_OFFSET
            ldr     r0, [r0]            /* r0 = offset value */
            ldrb    r4, [r5, r0]        /* r4 = current_partition (callee-saved) */

            /* Skip save if current_partition == 0xFF (first switch) */
            cmp     r4, #0xFF
            beq     .Lpendsv_dyn_skip_save

            /* Save outgoing partition context: r0 = partition index */
            mov     r0, r4
            bl      pendsv_context_save

        .Lpendsv_dyn_skip_save:
            /* Program MPU regions for incoming partition */
            bl      __pendsv_program_mpu

            /* Load next_partition: kernel_base + KERNEL_CORE_OFFSET + CORE_NEXT_PARTITION_OFFSET */
            ldr     r0, =KERNEL_CORE_OFFSET
            ldr     r0, [r0]            /* r0 = core offset */
            add     r6, r5, r0          /* r6 = &kernel.core */

            ldr     r0, =CORE_NEXT_PARTITION_OFFSET
            ldr     r0, [r0]            /* r0 = next_partition offset within core */
            ldrb    r4, [r6, r0]        /* r4 = next_partition (callee-saved) */

            /* Store next_partition to current_partition */
            ldr     r0, =KERNEL_CURRENT_PARTITION_OFFSET
            ldr     r0, [r0]            /* r0 = current_partition offset */
            strb    r4, [r5, r0]        /* current_partition = next_partition */

            /* Restore incoming partition context: r0 = partition index */
            mov     r0, r4
            bl      pendsv_context_restore

            /* pendsv_return_unprivileged does not return */
            bl      pendsv_return_unprivileged

            .size PendSV, . - PendSV
        "#
        );
    };
}
