//! Unified kernel state storage with linker-controlled placement.
//!
//! Provides [`UnifiedKernel`] type alias for the merged kernel state, placed
//! at a linker-controlled address via `.kernel_state` for assembly access.
//!
//! # SAFETY — Why `static mut UNIFIED_KERNEL_STORAGE` Cannot Be Eliminated
//!
//! This module contains a `static mut` that stores the unified kernel state.
//! On stable Rust (as of 1.87), this cannot be replaced with safer alternatives
//! for the following reasons:
//!
//! ## Linker-Controlled Placement Requirement
//!
//! The `UNIFIED_KERNEL_STORAGE` static is placed in the `.kernel_state` linker
//! section via `#[link_section = ".kernel_state"]`. This provides a fixed,
//! known address (`__kernel_state_start` symbol) that assembly code in the
//! PendSV and SVC handlers can reference directly. Alternatives like
//! `Mutex<RefCell<T>>` or `OnceCell<T>` do not support `#[link_section]`
//! placement because they wrap the inner value in additional layers that
//! obscure the address.
//!
//! The linker script (`memory.x`) reserves a dedicated RAM region for kernel
//! state, ensuring it does not overlap with partition memory regions. This
//! separation is critical for MPU isolation: the kernel state lives in
//! privileged-only memory that partitions cannot access.
//!
//! ## Assembly Access Pattern
//!
//! The PendSV handler (in `pendsv.rs`) and SVC trampoline (in `svc.rs`) use
//! inline assembly that loads the kernel state pointer directly:
//!
//! ```text
//! ldr r0, =__kernel_state_start
//! ```
//!
//! This pattern requires the storage to have a stable, linker-visible symbol.
//! Rust's safe abstractions (`Mutex`, `RefCell`, `OnceCell`) add indirection
//! layers that would require additional dereferences in assembly, adding
//! latency to the context switch hot path.
//!
//! ## Initialization-Before-Use Invariant
//!
//! The `boot()` function (generated by `define_unified_harness!` in
//! `harness.rs`) enforces the initialization-before-use invariant:
//!
//! 1. **Single initialization**: `init_kernel_state()` is called exactly once
//!    from `main()` before `boot()` is invoked. This writes a valid `Kernel<'mem, C>`
//!    instance into `UNIFIED_KERNEL_STORAGE`.
//!
//! 2. **Interrupts disabled during init**: The initialization occurs before
//!    any exception handlers are enabled. `boot()` configures SysTick and
//!    triggers PendSV only after the kernel state is fully initialized.
//!
//! 3. **No access before init**: The `with_kernel()` and `with_kernel_mut()`
//!    accessors are only called from exception handlers (SVC, SysTick, PendSV),
//!    which cannot run until after `boot()` enables them.
//!
//! ## Critical Section Protection
//!
//! All runtime access to `UNIFIED_KERNEL_STORAGE` goes through `with_kernel()`
//! or `with_kernel_mut()`, which wrap access in `cortex_m::interrupt::free()`.
//! This masks all configurable interrupts on single-core Cortex-M, preventing
//! concurrent access from different exception handlers. The exception priority
//! model provides additional protection:
//!
//! - **SVCall** runs at priority 0x00 (highest configurable)
//! - **SysTick** runs at priority 0x10
//! - **App IRQs** run at priority >= 0x20
//! - **PendSV** runs at priority 0xFF (lowest)
//!
//! This three-tier priority model ensures that SVCall (synchronous syscalls)
//! has the highest priority, SysTick (tick processing) preempts application
//! IRQs but not SVCall, and PendSV (context switch) runs at the lowest
//! priority. The critical section prevents any preemption during kernel
//! state access.
//!
//! ## Stable Rust Constraints
//!
//! On stable Rust, the following alternatives are unavailable or insufficient:
//!
//! - `static_cell::StaticCell`: Requires nightly or runtime checks that add
//!   overhead to the exception hot path.
//! - `OnceCell`/`OnceLock`: Do not support `#[link_section]` placement and
//!   add runtime initialization checks on every access.
//! - `Mutex<RefCell<Option<T>>>`: Does not support `#[link_section]` for the
//!   inner `T`, and the `Option` adds a branch on every access.
//!
//! The `static mut` pattern with explicit safety documentation is the standard
//! approach used by embedded Rust RTOSes (RTIC, Embassy, Hubris) for similar
//! reasons.
//!
//! ## Summary of Safety Invariants
//!
//! | Invariant | Enforced By |
//! |-----------|-------------|
//! | Single initialization | `init_kernel_state()` called once in `main()` |
//! | Init before use | `boot()` enables interrupts after init completes |
//! | No concurrent access | `cortex_m::interrupt::free()` in accessors |
//! | Linker placement | `#[link_section = ".kernel_state"]` attribute |
//! | Assembly visibility | `__kernel_state_start` symbol in linker script |

use core::mem::{align_of, size_of, MaybeUninit};
use core::ptr::addr_of_mut;
use core::sync::atomic::{AtomicBool, Ordering};

use crate::config::KernelConfig;
use crate::svc::Kernel;

/// Maximum size in bytes for kernel state storage.
///
/// This must be large enough to hold `Kernel<'mem, C>` for any configuration used.
/// The `init_kernel_state` function includes a compile-time assertion to verify
/// that the actual kernel size does not exceed this limit.
///
/// Current allocation: 32 KiB, sufficient for configurations such as
/// Partitions2 × AlignedStack4K (2 × 4 KiB = 8 KiB for stacks) as well as
/// up to 4 partitions using `AlignedStack1K`, plus metadata, schedule entries,
/// and moderate IPC pool sizes. For larger configurations, increase this value
/// and ensure the target has sufficient RAM.
///
/// # Relationship to literal-pool offset limit
///
/// `MAX_KERNEL_SIZE` (32 KiB) and [`LITERAL_POOL_OFFSET_LIMIT`](crate::pendsv::LITERAL_POOL_OFFSET_LIMIT)
/// (64 KiB) are **independent constraints**. `MAX_KERNEL_SIZE` governs
/// how much RAM is reserved for the entire `Kernel<'mem, C>` struct, while the
/// literal-pool offset limit is a conservative sanity-check for struct
/// field offsets accessed by PendSV assembly (which uses literal-pool
/// indirection, not Thumb2 imm12 encoding).
/// The `define_pendsv!(@assert_offsets)` macro enforces this at compile time.
pub const MAX_KERNEL_SIZE: usize = 32 * 1024;

/// Generates an alignment constant and a storage struct from a single
/// alignment literal, eliminating manual synchronization.
///
/// `#[repr(align(...))]` requires a literal, so the alignment value cannot
/// reference a `const`. This macro expands the same literal into both the
/// `const` and the `repr` attribute, making desynchronization impossible.
///
/// # Generated items
///
/// - `pub const $const_name: usize = $align;`
/// - `#[repr(C, align($align))] pub struct $name` with a `[u8; $size]` payload
/// - Compile-time assertion that the struct's actual alignment equals `$const_name`
macro_rules! define_aligned_storage {
    ($const_name:ident, $name:ident, $align:literal, $size:expr) => {
        /// Required alignment for the storage struct in bytes.
        pub const $const_name: usize = $align;

        /// Properly-aligned byte buffer whose size and alignment are set by the
        /// `define_aligned_storage!` invocation.
        #[repr(C, align($align))]
        pub struct $name {
            _data: [u8; $size],
        }

        // Compile-time assertion: alignment constant must match actual type alignment.
        // Belt-and-suspenders check — the macro guarantees this by construction,
        // but the assertion catches compiler/toolchain surprises.
        const _: () = assert!(
            core::mem::align_of::<$name>() == $const_name,
            concat!(
                stringify!($const_name),
                " constant does not match ",
                stringify!($name),
                " repr(align) value"
            )
        );
    };
}

define_aligned_storage!(KERNEL_ALIGNMENT, KernelStorageBuffer, 4096, MAX_KERNEL_SIZE);

/// Check pointer alignment to [`KERNEL_ALIGNMENT`]. Returns `Err(offset)` if misaligned.
#[inline]
fn check_kernel_alignment(ptr: *const u8) -> Result<(), usize> {
    match ptr as usize % KERNEL_ALIGNMENT {
        0 => Ok(()),
        offset => Err(offset),
    }
}

/// Static storage for the unified kernel state.
///
/// Uses a byte array wrapped in `MaybeUninit` for deferred initialization.
/// Linker places this in `.kernel_state` section (defined in `memory.x`),
/// providing a fixed address that assembly can reference via `__kernel_state_start`.
///
/// # Safety
///
/// Uninitialized at startup. Call [`init_kernel_state`] exactly once before
/// access. Reading before initialization is undefined behavior.
#[link_section = ".kernel_state"]
pub static mut UNIFIED_KERNEL_STORAGE: MaybeUninit<KernelStorageBuffer> = MaybeUninit::uninit();

/// Set once by [`init_kernel_state_at`] after successful initialization.
static KERNEL_INITIALIZED: AtomicBool = AtomicBool::new(false);

/// Minimum alignment required by the ARMv7-M MPU for kernel state region.
///
/// The MPU requires power-of-two-sized regions aligned to their own size.
/// The kernel state region is 4096 bytes minimum, so the buffer must be
/// at least 4096-byte aligned regardless of what `KERNEL_ALIGNMENT` is set to.
const MPU_MIN_ALIGNMENT: usize = 4096;

// Compile-time assertion: KernelStorageBuffer alignment must meet MPU hardware requirement.
// This is independent of KERNEL_ALIGNMENT — it enforces the MPU's minimum directly,
// catching regressions even if both KERNEL_ALIGNMENT and repr(align) are lowered together.
const _: () = assert!(
    core::mem::align_of::<KernelStorageBuffer>() >= MPU_MIN_ALIGNMENT,
    "KernelStorageBuffer alignment must be >= 4096 for MPU compatibility"
);

// Compile-time assertion: MAX_KERNEL_SIZE must be a power of two.
// ARMv7-M MPU regions must be power-of-two sized. If the kernel state is protected
// by an MPU region, its backing storage must satisfy this constraint.
const _: () = assert!(
    MAX_KERNEL_SIZE.is_power_of_two(),
    "MAX_KERNEL_SIZE must be a power of two for MPU region compatibility"
);

// Compile-time assertion: MAX_KERNEL_SIZE must be >= KERNEL_ALIGNMENT.
// An MPU region must be at least as large as its alignment. If MAX_KERNEL_SIZE were
// reduced below KERNEL_ALIGNMENT, the MPU region configuration would be invalid.
const _: () = assert!(
    MAX_KERNEL_SIZE >= KERNEL_ALIGNMENT,
    "MAX_KERNEL_SIZE must be >= KERNEL_ALIGNMENT for valid MPU region configuration"
);

// Compile-time assertion: MAX_KERNEL_SIZE must be <= LITERAL_POOL_OFFSET_LIMIT.
// PendSV and SVC handlers use literal-pool indirection (`ldr Rx, =SYMBOL`) to access
// Kernel fields. If MAX_KERNEL_SIZE exceeded the literal-pool offset limit (65536),
// field offsets could be unreachable and the generated assembly would silently break.
const _: () = assert!(
    MAX_KERNEL_SIZE <= crate::pendsv::LITERAL_POOL_OFFSET_LIMIT,
    "MAX_KERNEL_SIZE must be <= LITERAL_POOL_OFFSET_LIMIT to keep PendSV/SVC offsets valid"
);

// Compile-time assertion: KERNEL_ALIGNMENT must be >= the alignment of every stack tier.
// Stack tiers are embedded inside Kernel<'_, C> via PartitionCore, so the kernel storage
// buffer must be aligned at least as strictly as the most-aligned tier. If a future
// tier is added with alignment > KERNEL_ALIGNMENT, this fires at compile time.
const _: () = {
    use crate::partition_core::{
        AlignedStack1K, AlignedStack256B, AlignedStack2K, AlignedStack4K, AlignedStack512B,
    };
    macro_rules! check_align {
        ($tier:ty) => {
            assert!(
                KERNEL_ALIGNMENT >= core::mem::align_of::<$tier>(),
                concat!(
                    "KERNEL_ALIGNMENT must be >= ",
                    stringify!($tier),
                    " alignment"
                )
            );
        };
    }
    check_align!(AlignedStack256B);
    check_align!(AlignedStack512B);
    check_align!(AlignedStack1K);
    check_align!(AlignedStack2K);
    check_align!(AlignedStack4K);
};

/// Unified kernel state containing all kernel subsystems.
///
/// Merges: partitions, schedule, current/next indices, partition SPs, tick,
/// yield flag, and all IPC pools (events, semaphores, mutexes, messages,
/// queuing ports, sampling ports, blackboards). The `Kernel<'mem, C>` struct
/// already contains all these via sub-struct composition.
pub type UnifiedKernel<'mem, C> = Kernel<'mem, C>;

/// Helper struct for compile-time kernel storage invariants.
///
/// Verifies at compile time that `Kernel<'_, C>` fits within `MAX_KERNEL_SIZE`
/// and that its alignment does not exceed `KERNEL_ALIGNMENT`.
struct AssertKernelInvariants<C: KernelConfig>
where
    [(); C::N]:,
    [(); C::SCHED]:,
    #[cfg(feature = "dynamic-mpu")]
    [(); C::BP]:,
    #[cfg(feature = "dynamic-mpu")]
    [(); C::BZ]:,
    #[cfg(feature = "dynamic-mpu")]
    [(); C::DR]:,
{
    _marker: core::marker::PhantomData<C>,
}

impl<C: KernelConfig> AssertKernelInvariants<C>
where
    [(); C::N]:,
    [(); C::SCHED]:,
    #[cfg(feature = "dynamic-mpu")]
    [(); C::BP]:,
    #[cfg(feature = "dynamic-mpu")]
    [(); C::BZ]:,
    #[cfg(feature = "dynamic-mpu")]
    [(); C::DR]:,
{
    /// Zero-sized constant that only compiles if Kernel<'_, C> fits in storage
    /// and its alignment does not exceed the buffer alignment.
    const OK: () = {
        assert!(
            size_of::<Kernel<'_, C>>() <= MAX_KERNEL_SIZE,
            "Kernel<'_, C> exceeds MAX_KERNEL_SIZE"
        );
        assert!(
            align_of::<Kernel<'_, C>>() <= KERNEL_ALIGNMENT,
            "Kernel<'_, C> alignment exceeds KERNEL_ALIGNMENT"
        );
    };
}

/// Initialize kernel at `ptr`. Panics if misaligned.
/// # Safety
/// `ptr` must be valid, writable, and sized for `Kernel<'mem, C>`.
pub unsafe fn init_kernel_state_at<'mem, C: KernelConfig>(
    ptr: *mut Kernel<'mem, C>,
    kernel: Kernel<'mem, C>,
) -> Result<(), &'static str>
where
    [(); C::N]:,
    [(); C::SCHED]:,
    #[cfg(feature = "dynamic-mpu")]
    [(); C::BP]:,
    #[cfg(feature = "dynamic-mpu")]
    [(); C::BZ]:,
    #[cfg(feature = "dynamic-mpu")]
    [(); C::DR]:,
{
    if check_kernel_alignment(ptr as *const u8).is_err() {
        return Err("UNIFIED_KERNEL_STORAGE misaligned");
    }
    // Belt-and-suspenders: catch cases where Kernel<'_, C> requires more alignment than
    // KERNEL_ALIGNMENT. The check above validates against KERNEL_ALIGNMENT, but Kernel<'_, C>
    // could theoretically require stricter alignment if its internal types change.
    debug_assert!(
        ptr.is_aligned(),
        "ptr not aligned for Kernel<'_, C>: buffer alignment {} but type requires {} byte alignment",
        KERNEL_ALIGNMENT,
        align_of::<Kernel<'_, C>>()
    );
    // SAFETY: The caller guarantees that ptr is valid, writable, and has sufficient
    // size for Kernel<'_, C>. The alignment check above ensures ptr is KERNEL_ALIGNMENT-aligned.
    ptr.write(kernel);
    KERNEL_INITIALIZED.store(true, Ordering::Release);
    Ok(())
}

/// Initialize kernel state storage with a configured kernel instance.
///
/// # Safety
///
/// - Must be called exactly once before any other kernel access.
/// - The caller must ensure no other code accesses `UNIFIED_KERNEL_STORAGE`
///   during or after this call without proper synchronization.
///
/// # Panics
///
/// - Compile-time assertion fails if `size_of::<Kernel<'mem, C>>()` exceeds
///   [`MAX_KERNEL_SIZE`], or if `align_of::<Kernel<'mem, C>>()` exceeds
///   [`KERNEL_ALIGNMENT`].
/// - Runtime panic if `UNIFIED_KERNEL_STORAGE` address is not aligned to
///   [`KERNEL_ALIGNMENT`] (4096 bytes). The panic message includes the actual
///   alignment offset.
#[allow(dead_code)]
pub unsafe fn init_kernel_state<'mem, C: KernelConfig>(
    kernel: Kernel<'mem, C>,
) -> Result<(), &'static str>
where
    [(); C::N]:,
    [(); C::SCHED]:,
    #[cfg(feature = "dynamic-mpu")]
    [(); C::BP]:,
    #[cfg(feature = "dynamic-mpu")]
    [(); C::BZ]:,
    #[cfg(feature = "dynamic-mpu")]
    [(); C::DR]:,
{
    // Compile-time check: ensure Kernel<'mem, C> fits in the storage buffer and
    // its alignment does not exceed KERNEL_ALIGNMENT.
    #[allow(clippy::let_unit_value)]
    let _ = AssertKernelInvariants::<C>::OK;

    // SAFETY: The caller guarantees this is called exactly once before any
    // other kernel access. We use addr_of_mut! to obtain a raw pointer without
    // creating a reference to the static (avoiding static_mut_refs warning).
    //
    // The storage buffer is properly sized (MAX_KERNEL_SIZE bytes) and aligned
    // (KERNEL_ALIGNMENT-byte alignment via repr(C, align(...)). This alignment
    // matches the requirement of Kernel<'mem, C> which contains stack storage
    // fields that require KERNEL_ALIGNMENT-byte alignment. The compile-time
    // assertion above guarantees that Kernel<'mem, C> fits within this buffer. The
    // pointer cast from *mut MaybeUninit<KernelStorageBuffer> to
    // *mut MaybeUninit<Kernel<'mem, C>> is valid because:
    // 1. Both pointers point to the same memory location
    // 2. The buffer has sufficient size (verified at compile time)
    // 3. The buffer has sufficient alignment (KERNEL_ALIGNMENT >= Kernel<'mem, C> alignment)
    // 4. MaybeUninit::write() initializes the memory with a valid Kernel<'mem, C> value
    let mu_ptr = addr_of_mut!(UNIFIED_KERNEL_STORAGE) as *mut MaybeUninit<Kernel<'mem, C>>;

    // Alignment check: verify the storage address is KERNEL_ALIGNMENT-aligned.
    if check_kernel_alignment(mu_ptr as *const u8).is_err() {
        return Err("UNIFIED_KERNEL_STORAGE misaligned");
    }
    debug_assert!(
        mu_ptr.cast::<Kernel<'mem, C>>().is_aligned(),
        "ptr not aligned for Kernel<'mem, C>: buffer alignment {} but type requires {} byte alignment",
        KERNEL_ALIGNMENT,
        align_of::<Kernel<'mem, C>>()
    );

    // TODO: raw pointer deref needed because storage is type-erased (KernelStorageBuffer);
    // could be eliminated if UNIFIED_KERNEL_STORAGE were generic over Kernel<'mem, C>.
    // SAFETY: mu_ptr points to UNIFIED_KERNEL_STORAGE which has sufficient size
    // and alignment (verified above). We dereference the raw pointer to call
    // MaybeUninit::write(), which initializes the memory without reading it.
    unsafe { (*mu_ptr).write(kernel) };
    KERNEL_INITIALIZED.store(true, Ordering::Release);
    Ok(())
}

/// Get a raw pointer to the kernel state storage.
///
/// # Safety
///
/// The returned pointer is only valid after [`init_kernel_state`] has been called.
/// The caller must ensure proper synchronization when accessing the kernel state.
// TODO: reviewer false positive — get_kernel_ptr return type updated to 'static in commit d8d6a32
#[allow(dead_code)]
pub unsafe fn get_kernel_ptr<C: KernelConfig>() -> *mut Kernel<'static, C>
where
    [(); C::N]:,
    [(); C::SCHED]:,
    #[cfg(feature = "dynamic-mpu")]
    [(); C::BP]:,
    #[cfg(feature = "dynamic-mpu")]
    [(); C::BZ]:,
    #[cfg(feature = "dynamic-mpu")]
    [(); C::DR]:,
{
    // SAFETY: This function returns a raw pointer, deferring safety to the caller.
    // The pointer cast from *mut KernelStorageBuffer to *mut Kernel<'_, C> is valid
    // because init_kernel_state() wrote a Kernel<'_, C> at this location, and
    // KernelStorageBuffer has sufficient size (MAX_KERNEL_SIZE, verified at
    // compile time in init_kernel_state) and alignment (KERNEL_ALIGNMENT bytes
    // via repr(C, align(4096))). The caller must ensure init_kernel_state() was
    // called before dereferencing the returned pointer, and must provide proper
    // synchronization for access.
    let mu_ptr = addr_of_mut!(UNIFIED_KERNEL_STORAGE) as *mut MaybeUninit<Kernel<'_, C>>;
    // SAFETY: as_mut_ptr() returns pointer to inner value without assuming init.
    // TODO: raw pointer deref needed because storage is type-erased; see init_kernel_state.
    unsafe { (*mu_ptr).as_mut_ptr() }
}

/// Access the unified kernel state immutably within a critical section.
///
/// Wraps access to `UNIFIED_KERNEL_STORAGE` in `cortex_m::interrupt::free()`,
/// ensuring exclusive access by masking interrupts on single-core Cortex-M.
///
/// # Safety Invariants
///
/// This function is safe to call provided the following invariants hold:
///
/// 1. **Initialization before use**: `init_kernel_state()` must be called
///    exactly once by `boot()` before interrupts are enabled. The kernel
///    is initialized during the boot sequence before any exception handlers
///    can run.
///
/// 2. **Single-core execution**: Cortex-M is single-core; the critical section
///    via `interrupt::free()` masks all configurable interrupts, preventing
///    concurrent access from exception handlers.
///
/// 3. **Exception priority prevents reentrancy**: The three-tier priority
///    model ensures that lower-priority exceptions cannot preempt higher-priority
///    ones. SVCall runs at priority 0x00 (highest), SysTick at 0x10,
///    app IRQs at >= 0x20, and PendSV at 0xFF (lowest). This priority
///    ordering prevents reentrancy within kernel code paths.
///
/// # Returns
///
/// The result of applying closure `f` to a shared reference to the kernel.
///
/// # Safety
///
/// Calling this function before `init_kernel_state()` has been called results
/// in **Undefined Behavior** (dereferencing an uninitialized pointer).
// TODO: reviewer false positive — with_kernel closure lifetime updated to 'static in commit d8d6a32
#[cfg(not(test))]
pub fn with_kernel<C, F, R>(f: F) -> Result<R, &'static str>
where
    C: KernelConfig,
    F: FnOnce(&Kernel<'static, C>) -> R,
    [(); C::N]:,
    [(); C::SCHED]:,
    #[cfg(feature = "dynamic-mpu")]
    [(); C::BP]:,
    #[cfg(feature = "dynamic-mpu")]
    [(); C::BZ]:,
    #[cfg(feature = "dynamic-mpu")]
    [(); C::DR]:,
{
    if !KERNEL_INITIALIZED.load(Ordering::Acquire) {
        return Err("kernel not initialized");
    }
    Ok(cortex_m::interrupt::free(|_cs| {
        // SAFETY: KERNEL_INITIALIZED (Acquire) guarantees init_kernel_state()
        // completed (Release). Critical section prevents concurrent access.
        let mu_ptr = addr_of_mut!(UNIFIED_KERNEL_STORAGE) as *const MaybeUninit<Kernel<'_, C>>;
        // SAFETY: KERNEL_INITIALIZED guarantees the MaybeUninit was written.
        let kernel = unsafe { (*mu_ptr).assume_init_ref() };
        f(kernel)
    }))
}

/// Access the unified kernel state mutably within a critical section.
///
/// Wraps access to `UNIFIED_KERNEL_STORAGE` in `cortex_m::interrupt::free()`,
/// ensuring exclusive access by masking interrupts on single-core Cortex-M.
///
/// # Safety Invariants
///
/// This function is safe to call provided the following invariants hold:
///
/// 1. **Initialization before use**: `init_kernel_state()` must be called
///    exactly once by `boot()` before interrupts are enabled. The kernel
///    is initialized during the boot sequence before any exception handlers
///    can run.
///
/// 2. **Single-core execution**: Cortex-M is single-core; the critical section
///    via `interrupt::free()` masks all configurable interrupts, preventing
///    concurrent access from exception handlers.
///
/// 3. **Exception priority prevents reentrancy**: The three-tier priority
///    model ensures that lower-priority exceptions cannot preempt higher-priority
///    ones. SVCall runs at priority 0x00 (highest), SysTick at 0x10,
///    app IRQs at >= 0x20, and PendSV at 0xFF (lowest). This priority
///    ordering prevents reentrancy within kernel code paths.
///
/// # Returns
///
/// The result of applying closure `f` to a mutable reference to the kernel.
///
/// # Safety
///
/// Calling this function before `init_kernel_state()` has been called results
/// in **Undefined Behavior** (dereferencing an uninitialized pointer).
// TODO: reviewer false positive — with_kernel_mut closure lifetime updated to 'static in commit d8d6a32
#[cfg(not(test))]
pub fn with_kernel_mut<C, F, R>(f: F) -> Result<R, &'static str>
where
    C: KernelConfig,
    F: FnOnce(&mut Kernel<'static, C>) -> R,
    [(); C::N]:,
    [(); C::SCHED]:,
    #[cfg(feature = "dynamic-mpu")]
    [(); C::BP]:,
    #[cfg(feature = "dynamic-mpu")]
    [(); C::BZ]:,
    #[cfg(feature = "dynamic-mpu")]
    [(); C::DR]:,
{
    if !KERNEL_INITIALIZED.load(Ordering::Acquire) {
        return Err("kernel not initialized");
    }
    Ok(cortex_m::interrupt::free(|_cs| {
        // SAFETY: KERNEL_INITIALIZED (Acquire) guarantees init_kernel_state()
        // completed (Release). Critical section prevents concurrent access.
        let mu_ptr = addr_of_mut!(UNIFIED_KERNEL_STORAGE) as *mut MaybeUninit<Kernel<'_, C>>;
        // SAFETY: KERNEL_INITIALIZED guarantees the MaybeUninit was written.
        let kernel = unsafe { (*mu_ptr).assume_init_mut() };
        f(kernel)
    }))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        compose_kernel_config, DebugEnabled, MsgMinimal, Partitions2, PortsTiny, SyncMinimal,
    };

    compose_kernel_config!(TestConfig<Partitions2, SyncMinimal, MsgMinimal, PortsTiny, DebugEnabled>);

    /// Helper to create a test kernel instance.
    ///
    /// Abstracts cfg-gated construction logic for DRY compliance.
    fn create_test_kernel() -> Kernel<'static, TestConfig> {
        #[cfg(not(feature = "dynamic-mpu"))]
        {
            Kernel::new_empty()
        }
        #[cfg(feature = "dynamic-mpu")]
        {
            let reg = crate::virtual_device::DeviceRegistry::default();
            Kernel::new_empty(reg)
        }
    }

    #[test]
    fn unified_kernel_is_kernel_alias() {
        fn assert_same_type<T>(_: T, _: T) {}
        let k1: Kernel<'_, TestConfig> = create_test_kernel();
        let k2: UnifiedKernel<'_, TestConfig> = create_test_kernel();
        assert_same_type(k1, k2);
    }

    #[test]
    fn storage_is_in_kernel_state_section() {
        use core::ptr::addr_of;
        let ptr = addr_of!(UNIFIED_KERNEL_STORAGE);
        assert!(!ptr.is_null());
    }

    #[test]
    fn storage_buffer_has_correct_size() {
        assert_eq!(size_of::<KernelStorageBuffer>(), MAX_KERNEL_SIZE);
    }

    #[test]
    fn storage_buffer_size_is_power_of_two() {
        // Mirrors the compile-time const assertion for MAX_KERNEL_SIZE.
        // ARMv7-M MPU regions must be power-of-two sized, so the kernel
        // storage buffer must satisfy this constraint.
        assert!(
            MAX_KERNEL_SIZE.is_power_of_two(),
            "MAX_KERNEL_SIZE ({}) is not a power of two",
            MAX_KERNEL_SIZE
        );
    }

    #[test]
    fn kernel_fits_in_storage() {
        // Verify that Kernel<'_, TestConfig> fits in the storage buffer
        assert!(size_of::<Kernel<'_, TestConfig>>() <= MAX_KERNEL_SIZE);
    }

    #[test]
    fn storage_buffer_alignment() {
        use core::mem::align_of;
        // Verify alignment matches KERNEL_ALIGNMENT exactly.
        // This mirrors the compile-time const assertion in the module.
        assert_eq!(align_of::<KernelStorageBuffer>(), KERNEL_ALIGNMENT);
    }

    #[test]
    fn storage_buffer_mpu_alignment() {
        use core::mem::align_of;
        // Verify alignment meets the MPU hardware minimum (4096 bytes).
        // This mirrors the compile-time MPU_MIN_ALIGNMENT const assertion.
        assert!(align_of::<KernelStorageBuffer>() >= MPU_MIN_ALIGNMENT);
        // Also verify MPU_MIN_ALIGNMENT matches expected value.
        assert_eq!(MPU_MIN_ALIGNMENT, 4096);
    }

    #[test]
    #[allow(clippy::assertions_on_constants)]
    fn max_kernel_size_at_least_kernel_alignment() {
        // An MPU region must be at least as large as its alignment.
        // Mirrors the compile-time const assertion added to the module.
        assert!(
            MAX_KERNEL_SIZE >= KERNEL_ALIGNMENT,
            "MAX_KERNEL_SIZE ({}) must be >= KERNEL_ALIGNMENT ({})",
            MAX_KERNEL_SIZE,
            KERNEL_ALIGNMENT,
        );
    }

    #[test]
    #[allow(clippy::assertions_on_constants)]
    fn max_kernel_size_within_offset_limit() {
        // Mirrors the compile-time const assertion: MAX_KERNEL_SIZE must not
        // exceed LITERAL_POOL_OFFSET_LIMIT, otherwise PendSV/SVC literal-pool
        // indirection could become unreachable.
        assert!(
            MAX_KERNEL_SIZE <= crate::pendsv::LITERAL_POOL_OFFSET_LIMIT,
            "MAX_KERNEL_SIZE ({}) must be <= LITERAL_POOL_OFFSET_LIMIT ({})",
            MAX_KERNEL_SIZE,
            crate::pendsv::LITERAL_POOL_OFFSET_LIMIT,
        );
    }

    #[test]
    fn kernel_alignment_within_buffer_alignment() {
        assert!(align_of::<Kernel<'_, TestConfig>>() <= KERNEL_ALIGNMENT);
    }

    // NOTE: These alignment tests are unit tests rather than integration tests.
    // panic-halt is now an optional dependency, so integration tests in tests/ may
    // be feasible. Consider migrating these if integration test infrastructure is added.
    #[test]
    fn init_kernel_state_at_succeeds_with_aligned_pointer() {
        #[repr(C, align(4096))]
        struct AlignedStorage {
            data: MaybeUninit<[u8; MAX_KERNEL_SIZE]>,
        }
        let mut storage = AlignedStorage {
            data: MaybeUninit::uninit(),
        };
        let ptr = storage.data.as_mut_ptr() as *mut Kernel<'_, TestConfig>;
        let kernel = create_test_kernel();
        // SAFETY: ptr points to aligned, sufficiently-sized storage.
        let result = unsafe { init_kernel_state_at(ptr, kernel) };
        assert!(result.is_ok(), "expected Ok for aligned pointer");
    }

    #[test]
    fn init_kernel_state_at_returns_err_with_misaligned_pointer() {
        #[repr(C, align(4096))]
        struct AlignedStorage {
            data: MaybeUninit<[u8; MAX_KERNEL_SIZE + 4096]>,
        }
        let mut storage = AlignedStorage {
            data: MaybeUninit::uninit(),
        };
        let aligned_ptr = storage.data.as_mut_ptr() as *mut u8;
        // SAFETY: aligned_ptr has MAX_KERNEL_SIZE + 4096 bytes; offset 512 is in bounds.
        let misaligned_ptr = unsafe { aligned_ptr.add(512) } as *mut Kernel<'_, TestConfig>;
        let kernel = create_test_kernel();
        // SAFETY: Testing error on misaligned pointer; memory is valid but misaligned.
        let result = unsafe { init_kernel_state_at(misaligned_ptr, kernel) };
        assert!(result.is_err(), "expected Err for misaligned pointer");
        assert_eq!(result.unwrap_err(), "UNIFIED_KERNEL_STORAGE misaligned");
    }

    /// Summary test: exercises check_kernel_alignment with an aligned pointer (Ok)
    /// and 3+ misaligned offsets (Err), and verifies the constant relationships
    /// KERNEL_ALIGNMENT/MAX_KERNEL_SIZE/MPU_MIN_ALIGNMENT that mirror compile-time
    /// assertions.
    #[test]
    #[allow(clippy::assertions_on_constants)]
    fn alignment_pipeline_summary() {
        // --- Constant relationships (mirror compile-time assertions) ---
        assert!(
            KERNEL_ALIGNMENT.is_power_of_two(),
            "KERNEL_ALIGNMENT must be power of two"
        );
        assert!(
            MAX_KERNEL_SIZE.is_power_of_two(),
            "MAX_KERNEL_SIZE must be power of two"
        );
        assert!(MAX_KERNEL_SIZE >= KERNEL_ALIGNMENT);
        assert!(KERNEL_ALIGNMENT >= MPU_MIN_ALIGNMENT);

        // --- check_kernel_alignment with aligned pointer ---
        let aligned = (4 * KERNEL_ALIGNMENT) as *const u8;
        assert_eq!(check_kernel_alignment(aligned), Ok(()));

        // --- check_kernel_alignment with misaligned offsets ---
        // Use small offsets guaranteed to be < KERNEL_ALIGNMENT for any valid configuration.
        let offsets: [usize; 4] = [1, 3, 7, KERNEL_ALIGNMENT - 1];
        for off in offsets {
            let misaligned = (4 * KERNEL_ALIGNMENT + off) as *const u8;
            assert_eq!(
                check_kernel_alignment(misaligned),
                Err(off),
                "Expected Err({off}) for offset {off}"
            );
        }
    }

    /// Verifies that Kernel<'_, TestConfig> type alignment and size fit within
    /// the storage constants.
    #[test]
    fn kernel_type_fits_storage_constants() {
        assert!(
            KERNEL_ALIGNMENT >= align_of::<Kernel<'_, TestConfig>>(),
            "KERNEL_ALIGNMENT ({}) < Kernel<'_, TestConfig> alignment ({})",
            KERNEL_ALIGNMENT,
            align_of::<Kernel<'_, TestConfig>>(),
        );
        assert!(
            MAX_KERNEL_SIZE >= size_of::<Kernel<'_, TestConfig>>(),
            "MAX_KERNEL_SIZE ({}) < Kernel<'_, TestConfig> size ({})",
            MAX_KERNEL_SIZE,
            size_of::<Kernel<'_, TestConfig>>(),
        );
    }

    /// Verify define_aligned_storage! generates matching const and struct
    /// alignment by invoking it with independent arguments in a local module.
    #[test]
    fn define_aligned_storage_macro_generates_matching_items() {
        mod local {
            define_aligned_storage!(TEST_ALIGNMENT, TestBuffer, 512, 1024);
        }
        assert_eq!(local::TEST_ALIGNMENT, 512);
        assert_eq!(
            core::mem::align_of::<local::TestBuffer>(),
            512,
            "struct alignment must equal the literal passed to the macro"
        );
        assert_eq!(core::mem::size_of::<local::TestBuffer>(), 1024);
    }

    #[cfg(feature = "dynamic-mpu")]
    #[test]
    fn run_bottom_half_macro_sets_and_clears_flag() {
        let mut k = create_test_kernel();
        assert!(!k.in_bottom_half);
        let _bh = crate::run_bottom_half!(k, 0, &k.dynamic_strategy).unwrap();
        assert!(!k.in_bottom_half);
    }

    #[cfg(feature = "dynamic-mpu")]
    #[test]
    fn run_bottom_half_macro_returns_err_on_nested_call() {
        let mut k = create_test_kernel();
        k.in_bottom_half = true;
        let result = crate::run_bottom_half!(k, 0, &k.dynamic_strategy);
        assert_eq!(
            result.unwrap_err(),
            "nested bottom-half invocation detected"
        );
    }

    /// Verifies the init_kernel_state_at + assume_init_ref round-trip on
    /// aligned storage, mirroring the actual production write/read path.
    #[test]
    fn init_kernel_state_at_then_assume_init_ref_round_trip() {
        #[repr(C, align(4096))]
        struct Aligned(MaybeUninit<[u8; MAX_KERNEL_SIZE]>);
        let mut storage = Aligned(MaybeUninit::uninit());

        let ptr = storage.0.as_mut_ptr() as *mut Kernel<'_, TestConfig>;
        let kernel = create_test_kernel();
        // SAFETY: ptr is aligned and storage is large enough for Kernel<'_, TestConfig>.
        let result = unsafe { init_kernel_state_at(ptr, kernel) };
        assert!(result.is_ok(), "init_kernel_state_at must succeed");

        // Read back via MaybeUninit::assume_init_ref, same path as with_kernel.
        let mu_ptr = storage.0.as_ptr() as *const MaybeUninit<Kernel<'_, TestConfig>>;
        // SAFETY: init_kernel_state_at wrote a valid Kernel<'_, TestConfig> above.
        let recovered = unsafe { (*mu_ptr).assume_init_ref() };
        assert_eq!(
            recovered.current_partition, 255,
            "current_partition sentinel must survive round-trip"
        );
        assert!(
            recovered.active_partition.is_none(),
            "active_partition must be None after init"
        );
        assert_eq!(
            recovered.ticks_dropped, 0,
            "ticks_dropped must be zero after init"
        );
    }
}
